//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        string[] GetProducts(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<string[]> GetProductsAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(sysnova.Infrastructure.Errors.GlobalErrorDetails), Action="http://tempuri.org/IService1/GetCategoriesGlobalErrorDetailsFault", Name="GlobalErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/sysnova.Infrastructure.Errors")]
        string[] GetCategories(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAdd", ReplyAction="http://tempuri.org/IService1/DoAddResponse")]
        string DoAdd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAdd", ReplyAction="http://tempuri.org/IService1/DoAddResponse")]
        System.Threading.Tasks.Task<string> DoAddAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAddCloud", ReplyAction="http://tempuri.org/IService1/DoAddCloudResponse")]
        string DoAddCloud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAddCloud", ReplyAction="http://tempuri.org/IService1/DoAddCloudResponse")]
        System.Threading.Tasks.Task<string> DoAddCloudAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAddHelpDesk", ReplyAction="http://tempuri.org/IService1/DoAddHelpDeskResponse")]
        string DoAddHelpDesk();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoAddHelpDesk", ReplyAction="http://tempuri.org/IService1/DoAddHelpDeskResponse")]
        System.Threading.Tasks.Task<string> DoAddHelpDeskAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientWCF.ServiceReference1.IService1>, ClientWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetProducts(int value) {
            return base.Channel.GetProducts(value);
        }
        
        public System.Threading.Tasks.Task<string[]> GetProductsAsync(int value) {
            return base.Channel.GetProductsAsync(value);
        }
        
        public string[] GetCategories(int value) {
            return base.Channel.GetCategories(value);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync(int value) {
            return base.Channel.GetCategoriesAsync(value);
        }
        
        public string DoAdd() {
            return base.Channel.DoAdd();
        }
        
        public System.Threading.Tasks.Task<string> DoAddAsync() {
            return base.Channel.DoAddAsync();
        }
        
        public string DoAddCloud() {
            return base.Channel.DoAddCloud();
        }
        
        public System.Threading.Tasks.Task<string> DoAddCloudAsync() {
            return base.Channel.DoAddCloudAsync();
        }
        
        public string DoAddHelpDesk() {
            return base.Channel.DoAddHelpDesk();
        }
        
        public System.Threading.Tasks.Task<string> DoAddHelpDeskAsync() {
            return base.Channel.DoAddHelpDeskAsync();
        }
    }
}
